#!/usr/bin/env python3
import htcondor

coll = htcondor.Collector()
results = coll.query(htcondor.AdTypes.Schedd, "true", ["Name"])
for result in results:
    host = result["Name"]
    scheddAd = coll.locate(htcondor.DaemonTypes.Schedd, host)
    schedd = htcondor.Schedd(scheddAd)
    try:
        ajobs = schedd.query('JobStatus == 2 && CurrentTime - EnteredCurrentStatus > 345600', ["JobStatus"])
    except:
        print ('# Unable to query schedd:',host,'but continuing anyway')

    num = 0
    for ajob in ajobs:
        num += 1

    print ('JobsTooLong,schedd=%s value=%d' % (host, num))
