#!/usr/bin/python
import datetime
from datetime import datetime, timedelta
import socket
import subprocess
import sys
import subprocess, re

logfile = '/var/log/squid/access.log'
timeformat = '%d/%b/%Y:%H:%M'
delta = timedelta(minutes=-1)

now = datetime.now()
then = now + delta
timeString = then.strftime(timeformat)

# Stats from log file
try:
    f = open(logfile)
except:
    raise IOError('Unable to open squid access log file')

counts = {'atlas': 0, 'cms': 0, 'cvmfs': 0, 'cernvm': 0}

for line in f:
    if timeString in line:
        if 'cernvm' in line:
            counts['cernvm'] += 1
        elif 'cvmfs' in line:
            counts['cvmfs'] += 1
        else:
            if 'atlas' in line:
               counts['atlas'] += 1
            elif 'cms' in line:
               counts['cms'] += 1

f.close()

data = ''
for type, count in counts.iteritems():
    data += 'access,type=' + type + ' value=' + str(count) + '\n'

print data
